### ISSUE TITLE
TODO: dealing with loading xml for haarcascade, emember to update a texture, not create new textures every time... (texture observer)

### ISSUE THREAD

**Issue by ShootingStarDragon** [ShootingStarDragon/FastCVApp#154]
WHAT HAPPENED:
in openread I kept on importing fileVideoStream, that lagged it out bad enough to not keep reading fast. 
PLAN:
- [x] clean out code
- [x] ~subprocesses not exiting when i exit kivy~ > sent to #157
- [x] store bytes in sharedmem
- [ ] make sure logging is put in place to warn me if: computer vision is lagging, lagging frames, etc
2 examples to clear
- [ ] loading xml for haarcascade
- [ ] mediapipe
new problem: 
- [ ] i hit 30fps, and now the code uses A LOT of cpu, if ur cpu isn't super strong it will fail.... (resizing to 720p will make it easier on the cpu tho, this is something to keep in mind)

![Image](https://user-images.githubusercontent.com/61223134/233607750-6dbef284-152b-45d9-8d12-a0546c92c1d9.png)

- [ ] remember to update a texture, not create new textures every time...

**Comment by ShootingStarDragon** [comment]
- [ ] # I think creating a new texture is lagging the app, opencv reads the file faster than the video ends
                                # reference this, u need a reload observer: https://stackoverflow.com/questions/51546327/in-kivy-is-there-a-way-to-dynamically-change-the-shape-of-a-texture
                                # for later, if I need to clear a texture this is the reference: https://stackoverflow.com/questions/55099463/how-to-update-a-texture-from-array-in-kivy
