### ISSUE TITLE
start function requirements:

### ISSUE THREAD

**Issue by ShootingStarDragon** [ShootingStarDragon/FastCVApp#275]
- [x] START (works) < received from #199
	- [x] real question is how to supply the source?
		- [x] GUI: 
		- [x] Plan: add these 3 methods and set FVCA Widget source
		- [x] that's too much work for no gain: Focus on drag and drop, only allow mp4, webm, mkv, etc
			- [x] PROBLEMS:
				- [x] FPS is gonna be wrekt, so is the dimensions... (kinda not? since I force resize to 720p atm)
		- [x] filepicker SKIPPED
			- [x] (try on mac) https://kivy.org/doc/stable/api-kivy.uix.filechooser.html 
			- [x] > confirmed work as per https://github.com/ShootingStarDragon/FastCVApp/blob/windows/%23275/test/2023%20Jun%2021%20testing%20texture%20onupdate/filechooserexampleApp.py
		- [x] drag and drop from desktop...
			- [x] (try on mac) https://kivy.org/doc/stable/api-kivy.core.window.html#kivy.core.window.WindowBase.on_drop_file 
			- [x] > confirmed work as per https://github.com/ShootingStarDragon/FastCVApp/blob/windows/%23275/test/2023%20Jun%2021%20testing%20texture%20onupdate/dropapptest.py
		- [x] take a file-like as input SKIPPED
			- [x] https://stackoverflow.com/questions/13329445/how-to-read-image-from-in-memory-buffer-stringio-or-from-url-with-opencv-pytho
			- [x] https://stackoverflow.com/questions/14439194/opencv-python-bindings-how-do-i-capture-an-image-from-memory
	- [x] (later: get from database for ADS)
	- [x] 	make a start function that: takes any file as input, ~and starts at a specified time, that way resume will work~ (just seek...)
	- [x] init:
		- [x] spin up subprocess if they aren't already started > easier thanks to #204
		- [x] set up shared dicts
	- [x] continue: > this is seek #209
		- [x] 1 sec buffer to read to the right spot
		- [x] play
