### ISSUE TITLE
dec 22 2023 PLAN

### ISSUE THREAD

**Issue by AccelQuasarDragon** [ShootingStarDragon/FastCVApp#407]
- [x] notes: #403 is relevant because fcva folder structure changed to have a bin folder... AKA I NEED THAT BRANCH TO POINT TO (do this after i make exe/dmg)
- [x] REQS:
	- [x] 3 days left: 
	- [x] 22
	- [x] 23
	- [x] 24
- [x] GOAL:
- [ ] make exe for windows (can skip upx)
- [ ] make .dmg (which requires .app) for MAC
- [ ] writeup on itch
- [ ] post/announcement
	- [ ] why it took a long time
	- [ ] features (added features, slayed immortal bugs)
- [ ] JAN 9 2024:
	- [x] FOUND BUG #426
 - [ ] ALSO:
	- [x] document the process (it's been a pretty normal process so far)
	- [x] make sure that features work
	- [x] 3 days left
	- [x] 22
		- [x] GGs
	- [x] 23
		- [x] make windows exe and featuretest on vbox?
		- [x] fix problems on acer
		- [x] make it work
		- [x] I feel like the pose estimations are NOT synced, what I saw on ADS was NOT what I saw in gradedImages... DO LATER > #420
		- [x] make exe with pyinstaller > #364
			- [x] make sure exe clears images in gradedimages > #364 
				- [x] WIN
				- [x] MAC > #364
			- [x] clear images in gradedimages
			- [x] removing old files does not work with os.remove (it does, but im doing folder update multiples times, just clear when u fcvautils resource update)
			- [x] it collects the gradedImages on the dev environment AKA that's super bad
			- [x] 2 problems:
			- [x] didnt clear before making exe so images got packaged
			- [x] clearing old images didnt work either when running exe on vbox > now it does
			- [x] images did get removed, but got copied over repeatedly so the last copy did not get deleted, anyways shouldn't have those images AT ALL
			- [x] tested suspicion w.r.t. ordering by doing print statements > if that is the problem update/fix it then update specfile to delete images then make exe file
			- [x] score is weirdly high for some reason, should be low 10% but it's basically 90% DO LATER #421
			- [x] do check where 1: gradedimages is cleared when making exe/app through specfile  
			- [x] 2nd check: distributable removed files on 1st run in gradedimages
		- [x] check features > #364
		- [x] do w/o venv? -- 12/30/2023 ????what does w/o venv mean?
		- [x] REMINDER: > #364
			- [x] turn off console > #364
			- [x] go fullscreen mode > #364
		- [x] make mac .app> #364
	- [x] 24

**Comment by AccelQuasarDragon** [comment]
.
