### ISSUE TITLE
clearing up feature/#25

### ISSUE THREAD

**Issue by ShootingStarDragon** [ShootingStarDragon/FastCVApp#88]
- [x] sidetracked, doing: https://github.com/ShootingStarDragon/FastCVApp/issues/80
	- [x] yeah, the problem wasn't the code but that I conflate "run_state" and "fullSTOP" now... time to clean it up. in any case, I got it to exit gracefully now mar 16 23
	- [x] ask filipe, it's super spooky even the example fails to exit properly... https://stackoverflow.com/questions/31458331/running-multiple-kivy-apps-at-same-time-that-communicate-with-each-other
	- [x] I'm dumb, I was importing it in importFCVA.py and it wasn't exiting itself, the module code works I think
	- [x] another problem is I actually use run_state and fullSTOP,  make it easier to understand...
	- [x] I know the problem for the media subprocess, it's stuck in the inner loop introduced by mediapipe....
	- [x] another thing to pre-clear, name the subprocess so kivy only loads in that subprocess
	- [x] I think I need to stop the while loops in the actual subprocess targets, I tried to force exit with .join(1) for a 1 sec timeout and still got an error, just modify the target code a little bit so the while loops break or smth like that
	- [x] error is that the subprocesses are running kivy and aren't getting the close message somehow? not sure
- [x] need to be able to set the source
- [x] set the source file so FCVA will run
- [x] set fps as an option #32
- [x] am i reading at the right frame rate? how do codecs do this (display at the right frame rate)? made into it's own issue [#83](https://github.com/ShootingStarDragon/FastCVApp/issues/83)
- [x] need to strip out everything to the barest minimal code then put back in the notes
- [x] also too many flags, either find a way to get rid of them or at least document them (flags are documented)
- [x] share orientation between opencv VS kivy blit buffer
- [ ] 
- [ ] 
- [ ] CLEANING OUT MINIMAL EXAMPLE:
- [x] delete unnecessary comments on module and test file
- [x] make example run mediapipe
	- [x] problem is that running mp is different from doing a frame by frame analysis since u use the with holsitic block...
	- [x] the assumption is mycvfunc is run on a per frame basis, but the holistic block wants to be the entire block.... thinking then if u want it to be the whole block u must accept these "internal" vars which is not ok as a module: shared_analysis_dict, shared_metadata_dict, appliedcv. shared_metadata_dict["mp_ready"]
	- [x] I think u can still pass the with holistic block as the applied cv func, it will be lame having a while True, with holistic but I think it will work
	- [x] OK, really ended up stacking while True, with holistic AND THEN so that holistic doesn't open again, while True. WTFFFFFFFFFFF. that's not ok. question is: how to run opencv func repeatedly, and as fast as possible? also how to run with holistic once, and possibly replace while True? maybe I can at least get rid of the 1st outer while True? unsure
	- [x] instead of while true, at least a while condition so the app exists gracefully. i think stacking is tolerable for now, because you really DO need to run code as fast as possible, and you need to make sure holistic isn't opened on every block. 
	- [x] the ONE caveat is that for the mediapipe example, it must return the answer to shared_analysis_dict... RIP
	- [x] kinda doomed, I think you should just give the references to the shared memory, similar to how object methods must accept self. 	
- [x] then do a canny edge detector example, sent to it's own issue, #84
- [x] in the module, there is an if name == module check, (finalized, appname is FastCVApp)
- [x] rename app.AFTERrun
- [x] #this is why it's loading multiple times, need to name the subprocess and run only from there (fixed by putting the kivy class within the function definition of the subprocess target open_kivy)
- [ ]  
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]
